[package]
name = "lazycompass-mongo"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
mongodb = { workspace = true }
tokio = { workspace = true }
lazycompass-core = { path = "../lazycompass-core" }
